 1:CREATE DATABASE:---

 CREATE DATABASE cods;
 
 2:CREATE TABLE:---
 
 CREATE TABLE IF NOT EXISTS `contactForm` (
   `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
   `name` VARCHAR(255),
   `phone`
 ) ENGINE = InnoDB;
 

